name: Update Burndown Chart

on:
  issues:
    types: [opened, closed, reopened, deleted]
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-burndown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -r burndown/requirements.txt
      
      - name: Fetch issues from GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          python3 burndown/scripts/fetch_issues.py
      
      - name: Generate burndown chart
        run: |
          python3 burndown/scripts/generate_burndown_chart.py
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add burndown/ || true
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Auto-update burndown chart [skip ci]" && git push)
